DETECTION_MODEL = "fede-m/fairly_test_model"
TOKENIZER_MODEL = "osiria/roberta-base-italian"
# GENERATION_MODEL = "groq/llama-3.3-70b-versatile"
#GENERATION_MODEL = "SLURM.qwen3:32b-fp16"
GENERATION_MODEL = "SLURM.gpt-oss:120b"