DETECTION_MODEL = "fairly-org/fairly_detection_v0"
TOKENIZER_MODEL = "osiria/roberta-base-italian"
# GENERATION_MODEL = "groq/llama-3.3-70b-versatile"
#GENERATION_MODEL = "SLURM.utopia/qwen3.8:27b"
GENERATION_MODEL = "SLURM.utopia/gpt-oss:120b"